cucumber.features=src/test/java/features
cucumber.glue=stepdefinition,pages,utils
cucumber.plugin=pretty, html:target/cucumber-report.html, json:target/cucumber-report.json
cucumber.monochrome=true